/** Selected clients grid on the home page (order preserved). */
export const HOME_CLIENT_NAMES: readonly string[] = [
  'Vogue Paris',
  'Balenciaga',
  'Dazed & Confused',
  'SSENSE',
  'Maison Margiela',
  'Acne Studios',
  'Bottega Veneta',
  'The Row',
  'Dior Homme',
  'Phoebe Philo',
  'Kering Group',
  'AnOther Magazine',
  'Jil Sander',
  'Celine',
  'Rick Owens',
  'Saint Laurent',
  'Loewe',
  'Hermès',
  'Chanel',
  'Prada',
  'Valentino',
  'Givenchy',
  'Comme des Garçons',
  'Isabel Marant',
  'Jacquemus',
  'Lemaire',
  'Alaïa',
  'Miu Miu',
  'i-D Magazine',
  'Purple Magazine',
];
